export { default as Header } from './header/Header'
export { default as About } from './about/About'
export { default as Services } from './services/Services'
export { default as Pricing } from './pricing/Pricing'
export { default as Footer } from './footer/Footer'